#!/usr/bin/env bash
set -u

# Collect a read-only diagnostic snapshot for the HP Envy B&O Linux audio
# investigation. This script intentionally makes no system changes.

timestamp="$(date +%Y%m%d-%H%M%S)"
out="${1:-hp-envy-audio-${timestamp}}"

mkdir -p "$out"

run() {
    local name="$1"
    shift
    {
        printf '$'
        printf ' %q' "$@"
        printf '\n\n'
        "$@"
    } >"$out/$name.txt" 2>&1 || true
}

capture_file() {
    local source="$1"
    local target="$2"
    if [[ -r "$source" ]]; then
        cp "$source" "$out/$target" 2>/dev/null || true
    fi
}

{
    echo "Collected: $(date --iso-8601=seconds 2>/dev/null || date)"
    echo
    echo "This directory was generated by scripts/collect-audio-info.sh."
    echo "The collector is intended to be read-only."
} >"$out/README.txt"

run uname uname -a
run os-release cat /etc/os-release
run kernel-command-line cat /proc/cmdline
run lspci-audio lspci -nnk
run lsusb lsusb
run dmi-product bash -c 'for f in /sys/class/dmi/id/{sys_vendor,product_name,product_version,product_sku,board_vendor,board_name,bios_vendor,bios_version,bios_date}; do printf "%s: " "$f"; cat "$f" 2>/dev/null || true; done'

run proc-asound-cards cat /proc/asound/cards
run proc-asound-devices cat /proc/asound/devices
run proc-asound-modules cat /proc/asound/modules
run aplay-list aplay -l
run aplay-list-pcm aplay -L
run arecord-list arecord -l
run arecord-list-pcm arecord -L
run amixer amixer
run alsactl-info alsactl info

run pactl-info pactl info
run pactl-cards pactl list cards
run pactl-sinks pactl list sinks
run pactl-sources pactl list sources

run wpctl-status wpctl status
run wpctl-inspect-all bash -c 'wpctl status -n 2>/dev/null; echo; for id in $(wpctl status -n 2>/dev/null | grep -oE "[0-9]+\." | tr -d "." | sort -nu); do echo "===== wpctl inspect $id ====="; wpctl inspect "$id" 2>&1 || true; done'

run pipewire-version pipewire --version
run wireplumber-version wireplumber --version
run systemctl-user-audio systemctl --user --no-pager --full status pipewire.service pipewire-pulse.service wireplumber.service

run lsmod lsmod
run modinfo-snd-hda-intel modinfo snd_hda_intel
run modinfo-snd-sof-pci-intel-tgl modinfo snd_sof_pci_intel_tgl
run modinfo-snd-sof-pci-intel-mtl modinfo snd_sof_pci_intel_mtl

run dmesg-audio bash -c 'dmesg 2>&1 | grep -Ei "snd|sof|sound|audio|codec|hda|cs35|tas|rt[0-9]|alc[0-9]"'
run journal-kernel-audio bash -c 'journalctl -b -k --no-pager 2>&1 | grep -Ei "snd|sof|sound|audio|codec|hda|cs35|tas|rt[0-9]|alc[0-9]"'
run journal-user-audio journalctl --user -b --no-pager -u pipewire -u pipewire-pulse -u wireplumber

run firmware-audio bash -c 'find /lib/firmware -maxdepth 5 -type f \( -iname "*sof*" -o -iname "*cs35*" -o -iname "*audio*" -o -iname "*hda*" -o -iname "*tplg*" \) 2>/dev/null | sort'
run ucm-files bash -c 'find /usr/share/alsa/ucm /usr/share/alsa/ucm2 -maxdepth 6 -type f 2>/dev/null | sort'
run pipewire-config bash -c 'find /etc/pipewire /usr/share/pipewire -maxdepth 5 -type f 2>/dev/null | sort'
run wireplumber-config bash -c 'find /etc/wireplumber /usr/share/wireplumber -maxdepth 5 -type f 2>/dev/null | sort'

# Codec proc files are often the most useful evidence for HDA systems.
if [[ -d /proc/asound ]]; then
    while IFS= read -r -d '' codec; do
        safe="$(echo "$codec" | sed 's#^/proc/asound/##; s#[/ ]#_#g')"
        cp "$codec" "$out/codec-${safe}.txt" 2>/dev/null || true
    done < <(find /proc/asound -type f -name 'codec#*' -print0 2>/dev/null)
fi

# Preserve ALSA state if readable. This does not alter it.
capture_file /var/lib/alsa/asound.state alsa-state.txt

if command -v tar >/dev/null 2>&1; then
    tar -czf "$out.tar.gz" "$out" 2>/dev/null || true
fi

echo
echo "Audio diagnostic snapshot written to:"
echo "  $out"
if [[ -f "$out.tar.gz" ]]; then
    echo "  $out.tar.gz"
fi
