param(
    [string]$OutputDirectory = ("hp-envy-windows-audio-" + (Get-Date -Format "yyyyMMdd-HHmmss"))
)

$ErrorActionPreference = "SilentlyContinue"
New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

function Save-Text {
    param(
        [string]$Name,
        [scriptblock]$Script
    )
    $path = Join-Path $OutputDirectory ($Name + ".txt")
    try {
        & $Script 2>&1 | Out-String -Width 4096 | Set-Content -Path $path -Encoding UTF8
    } catch {
        $_ | Out-String | Set-Content -Path $path -Encoding UTF8
    }
}

Save-Text "computer-info" {
    Get-ComputerInfo |
        Select-Object CsManufacturer,CsModel,CsSystemSKUNumber,BiosManufacturer,BiosVersion,BiosReleaseDate,
                      WindowsProductName,WindowsVersion,OsBuildNumber,OsArchitecture
}

Save-Text "audio-pnp-devices" {
    Get-PnpDevice -PresentOnly |
        Where-Object {
            $_.Class -in @("MEDIA","AudioEndpoint","SoftwareComponent") -or
            $_.FriendlyName -match "Realtek|Intel.*Smart Sound|Bang|Olufsen|B&O|Audio|SST|DTS|Dolby"
        } |
        Sort-Object Class,FriendlyName |
        Format-Table -AutoSize -Wrap Status,Class,FriendlyName,InstanceId
}

Save-Text "audio-drivers" {
    Get-CimInstance Win32_PnPSignedDriver |
        Where-Object {
            $_.DeviceClass -in @("MEDIA","AudioEndpoint","SoftwareComponent") -or
            $_.DeviceName -match "Realtek|Intel.*Smart Sound|Bang|Olufsen|B&O|Audio|SST|DTS|Dolby"
        } |
        Sort-Object DeviceName |
        Select-Object DeviceName,DeviceClass,Manufacturer,DriverProviderName,DriverVersion,DriverDate,
                      InfName,DeviceID,Signer |
        Format-List
}

Save-Text "realtek-device-properties" {
    $dev = Get-PnpDevice -PresentOnly |
        Where-Object { $_.InstanceId -match "VEN_10EC&DEV_0245" -or $_.FriendlyName -match "Realtek.*Audio" }
    foreach ($d in $dev) {
        "=== $($d.FriendlyName) ==="
        "InstanceId: $($d.InstanceId)"
        Get-PnpDeviceProperty -InstanceId $d.InstanceId |
            Sort-Object KeyName |
            Format-Table -AutoSize -Wrap KeyName,Type,Data
    }
}

Save-Text "intel-sst-device-properties" {
    $dev = Get-PnpDevice -PresentOnly |
        Where-Object { $_.FriendlyName -match "Intel.*Smart Sound|SST" }
    foreach ($d in $dev) {
        "=== $($d.FriendlyName) ==="
        "InstanceId: $($d.InstanceId)"
        Get-PnpDeviceProperty -InstanceId $d.InstanceId |
            Sort-Object KeyName |
            Format-Table -AutoSize -Wrap KeyName,Type,Data
    }
}

Save-Text "software-components" {
    Get-PnpDevice -Class SoftwareComponent -PresentOnly |
        Sort-Object FriendlyName |
        Format-Table -AutoSize -Wrap Status,FriendlyName,InstanceId
}

Save-Text "installed-driver-packages-audio" {
    pnputil /enum-drivers |
        Select-String -Pattern "Published Name|Original Name|Provider Name|Class Name|Driver Version|Signer Name" -Context 0,0
}

Save-Text "audio-services" {
    Get-Service |
        Where-Object {
            $_.Name -match "Audio|Realtek|Rtk|Intel|SST|DTS|Dolby" -or
            $_.DisplayName -match "Audio|Realtek|Intel.*Smart Sound|Bang|Olufsen|DTS|Dolby"
        } |
        Sort-Object Name |
        Format-Table -AutoSize Status,StartType,Name,DisplayName
}

Save-Text "audio-related-software" {
    $paths = @(
        "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*",
        "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*"
    )
    Get-ItemProperty $paths |
        Where-Object {
            $_.DisplayName -match "Realtek|Intel.*Smart Sound|Bang|Olufsen|B&O|Audio|DTS|Dolby|HP Audio"
        } |
        Sort-Object DisplayName |
        Select-Object DisplayName,DisplayVersion,Publisher,InstallLocation |
        Format-Table -AutoSize -Wrap
}

Save-Text "device-manager-audio-summary" {
    Get-CimInstance Win32_SoundDevice |
        Select-Object Name,Manufacturer,Status,PNPDeviceID |
        Format-List
}

$readme = @"
Collected: $(Get-Date -Format o)

This directory was generated by scripts/collect-windows-audio-info.ps1.

The collector is read-only. It is intended to capture the known-good Windows
audio configuration for comparison with the CachyOS/Linux baseline.
"@
$readme | Set-Content -Path (Join-Path $OutputDirectory "README.txt") -Encoding UTF8

$zip = "$OutputDirectory.zip"
try {
    Compress-Archive -Path $OutputDirectory -DestinationPath $zip -Force
} catch {}

Write-Host ""
Write-Host "Windows audio diagnostic snapshot written to:"
Write-Host "  $OutputDirectory"
if (Test-Path $zip) {
    Write-Host "  $zip"
}
